### ISSUE TITLE
Not charging

### ISSUE THREAD

**Issue by heronlen** [tjohn327/raspberry_pi_ups#4]
Hi I received the PowerPi, all configured, as per instructions and it runs the Pi when the power is disconnected, however it isn't charging the battery.

Running nc -lvu  40001

Listening on [0.0.0.0] (family 2, port 40001)
Connection from localhost 46547 received!
{
    "BatteryPercentage": 30, 
    "BatteryVoltage": 3.504, 
    "ChargeCurrent": 0, 
    "ChargeStatus": "Not Charging", 
    "InputVoltage": 2.6, 
    "PowerInputStatus": "Not Connected", 
    "TimeRemaining": 26
}

Thanks in advance.

**Comment by kiddigital** [comment]
@heronlen , it also says that the PowerInputStatus is 'Not Connected'. So there is no power to charge from :)

Check the powersupply to the PowerPI to make sure the PowerPI gets power at all.

**Comment by heronlen** [comment]
Yes, saw that but how would I resolve a no power connected to the PowerPi when it is seated correctly and working the other way round?

**Comment by tjohn327** [comment]
@heronlen Power Pi is designed to be powered from the micro usb input port of Power Pi not from the usb input of the Raspberry Pi. Have you connected a power supply to the micro usb input of the Power Pi?  What is the rating of the power supply?

**Comment by heronlen** [comment]
@tjohn327 How stupid do I feel?!  Sorry about that.  I missed it in your instructions!  Thanks, all great now.

**Comment by tjohn327** [comment]
@heronlen no worries :) Hope you enjoy Power Pi
